[project]
name = "day-02-ai-todo-crud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.1",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
]
